In [4]:
from mootdx.quotes import Quotes

# 标准市场
client = Quotes.factory(market='std', multithread=True, heartbeat=True)

# k 线数据
client.bars(symbol='600036', frequency=9, offset=10)

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime,volume
datetime,,,,,,,,,,,,,
2026-05-08 15:00:00,38.03,37.94,38.18,37.90,869539.0,3.303687e+09,2026,5,8,15,0,2026-05-08 15:00,869539.0
2026-05-11 15:00:00,37.95,37.97,37.98,37.70,925489.0,3.502977e+09,2026,5,11,15,0,2026-05-11 15:00,925489.0
2026-05-12 15:00:00,37.98,37.90,38.14,37.86,967299.0,3.673345e+09,2026,5,12,15,0,2026-05-12 15:00,967299.0
2026-05-13 15:00:00,37.96,37.88,38.09,37.85,718304.0,2.723486e+09,2026,5,13,15,0,2026-05-13 15:00,718304.0
2026-05-14 15:00:00,37.81,37.81,38.02,37.73,867867.0,3.286218e+09,2026,5,14,15,0,2026-05-14 15:00,867867.0
2026-05-15 15:00:00,37.81,37.65,37.97,37.61,821737.0,3.101358e+09,2026,5,15,15,0,2026-05-15 15:00,821737.0
2026-05-18 15:00:00,37.65,37.47,37.66,37.35,707684.0,2.651017e+09,2026,5,18,15,0,2026-05-18 15:00,707684.0
2026-05-19 15:00:00,37.48,37.37,37.74,37.34,719910.0,2.698787e+09,2026,5,19,15,0,2026-05-19 15:00,719910.0
2026-05-20 15:00:00,37.37,37.17,37.44,37.17,693184.0,2.582330e+09,2026,5,20,15,0,2026-05-20 15:00,693184.0
2026-05-21 15:00:00,37.18,37.15,37.34,37.11,725199.0,2.698141e+09,2026,5,21,15,0,2026-05-21 15:00,725199.0

In [5]:
# 指数
client.index(symbol='000001', frequency=9)

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime,up_count,down_count,volume
datetime,,,,,,,,,,,,,,,
2023-02-01 15:00:00,3262.20,3284.92,3284.92,3245.41,3395094.0,4.133952e+11,2023,2,1,15,0,2023-02-01 15:00,1905,259,3395094.0
2023-02-02 15:00:00,3291.78,3285.67,3295.76,3272.41,3334131.0,4.286628e+11,2023,2,2,15,0,2023-02-02 15:00,1069,1055,3334131.0
2023-02-03 15:00:00,3275.66,3263.41,3275.66,3235.35,2933428.0,3.786485e+11,2023,2,3,15,0,2023-02-03 15:00,761,1380,2933428.0
2023-02-06 15:00:00,3244.70,3238.70,3250.35,3226.21,2670531.0,3.491273e+11,2023,2,6,15,0,2023-02-06 15:00,795,1318,2670531.0
2023-02-07 15:00:00,3245.23,3248.09,3250.03,3233.83,2509464.0,3.212576e+11,2023,2,7,15,0,2023-02-07 15:00,1433,683,2509464.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-05-15 15:00:00,4174.18,4135.39,4191.81,4114.09,7331623.0,1.519240e+12,2026,5,15,15,0,2026-05-15 15:00,753,1543,7331623.0
2026-05-18 15:00:00,4120.14,4131.53,4145.66,4108.60,6272331.0,1.315084e+12,2026,5,18,15,0,2026-05-18 15:00,1008,1271,6272331.0
2026-05-19 15:00:00,4122.96,4169.54,4170.29,4107.99,6176110.0,1.306522e+12,2026,5,19,15,0,2026-05-19 15:00,1559,738,6176110.0
2026-05-20 15:00:00,4152.70,4162.18,4169.85,4139.97,6241520.0,1.358927e+12,2026,5,20,15,0,2026-05-20 15:00,783,1533,6241520.0
2026-05-21 15:00:00,4174.38,4077.28,4199.53,4074.22,7272187.0,1.595727e+12,2026,5,21,15,0,2026-05-21 15:00,338,1987,7272187.0

In [1]:
from mootdx.quotes import Quotes
import pandas as pd

# 初始化行情
client = Quotes.factory(market='std', heartbeat=True)

# 获取最近一年日线（250根交易日K线）
df = client.bars(
    symbol="600036",   # 股票代码
    frequency=9,       # 9=日线
    offset=250         # 250根 ≈ 1年交易日
)

# 转DataFrame方便查看
df = pd.DataFrame(df)
print(df)

                      open  close   high    low       vol        amount  year  \
datetime
2025-05-12 15:00:00  43.45  43.80  44.40  43.11  848974.0  3.724155e+09  2025
2025-05-13 15:00:00  44.09  44.56  44.65  43.85  699124.0  3.099991e+09  2025
2025-05-14 15:00:00  44.55  44.81  45.30  44.32  712790.0  3.194544e+09  2025
2025-05-15 15:00:00  44.83  44.92  45.38  44.65  684600.0  3.080578e+09  2025
2025-05-16 15:00:00  44.75  44.27  44.98  44.03  619655.0  2.743751e+09  2025
...                    ...    ...    ...    ...       ...           ...   ...
2026-05-15 15:00:00  37.81  37.65  37.97  37.61  821737.0  3.101358e+09  2026
2026-05-18 15:00:00  37.65  37.47  37.66  37.35  707684.0  2.651017e+09  2026
2026-05-19 15:00:00  37.48  37.37  37.74  37.34  719910.0  2.698787e+09  2026
2026-05-20 15:00:00  37.37  37.17  37.44  37.17  693184.0  2.582330e+09  2026
2026-05-21 15:00:00  37.18  37.15  37.34  37.11  725199.0  2.698141e+09  2026

                     month  day  hour  minute          datetime    volume
datetime
2025-05-12 15:00:00      5   12    15       0  2025-05-12 15:00  848974.0
2025-05-13 15:00:00      5   13    15       0  2025-05-13 15:00  699124.0
2025-05-14 15:00:00      5   14    15       0  2025-05-14 15:00  712790.0
2025-05-15 15:00:00      5   15    15       0  2025-05-15 15:00  684600.0
2025-05-16 15:00:00      5   16    15       0  2025-05-16 15:00  619655.0
...                    ...  ...   ...     ...               ...       ...
2026-05-15 15:00:00      5   15    15       0  2026-05-15 15:00  821737.0
2026-05-18 15:00:00      5   18    15       0  2026-05-18 15:00  707684.0
2026-05-19 15:00:00      5   19    15       0  2026-05-19 15:00  719910.0
2026-05-20 15:00:00      5   20    15       0  2026-05-20 15:00  693184.0
2026-05-21 15:00:00      5   21    15       0  2026-05-21 15:00  725199.0

[250 rows x 13 columns]